server:
  port: 8070

#for discovery service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#spring properties
spring:
  application:
    #display name in Eureka
    name: schools
  #idk why...
  config:
    import: optional:configserver:http://localhost:8888
  #postgresql connecting
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/school
    username: postgres
    password: bestuser
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    studentsUrl: http://localhost:8222/api/v1/students

management:
  tracing:
    sampling:
      probability: 1.0